INSERT INTO AUTH.ROLES(id, name) VALUES(AUTH.ROLE_SEQ.NEXTVAL, 'ROLE_USER');
INSERT INTO AUTH.ROLES(id, name) VALUES(AUTH.ROLE_SEQ.NEXTVAL,'ROLE_MODERATOR');
INSERT INTO AUTH.ROLES(id, name) VALUES(AUTH.ROLE_SEQ.NEXTVAL,'ROLE_ADMIN');